-- =========================================================
-- FIX PAYMENT & ENROLLMENT SCHEMA
-- =========================================================
-- 1. FIX ENROLLMENTS "ID" (Enable Auto-Increment)
-- The table currently requires an ID but doesn't generate one.
-- We alter it to be an IDENTITY column.
DO $$ BEGIN
ALTER TABLE public.enrollments
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY;
EXCEPTION
WHEN OTHERS THEN NULL;
-- Ignore if already identity
END $$;
-- 2. FIX ORDERS VISIBILITY (RLS)
-- Ensure Admin can SEE the orders in the Dashboard.
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admin Full Access" ON public.orders;
CREATE POLICY "Admin Full Access" ON public.orders FOR ALL USING (
    auth.jwt()->>'email' = 'vishal.pandey1912@gmail.com'
) WITH CHECK (
    auth.jwt()->>'email' = 'vishal.pandey1912@gmail.com'
);
-- Also allow Users to read their own orders (Optional but good)
DROP POLICY IF EXISTS "Users read own orders" ON public.orders;
CREATE POLICY "Users read own orders" ON public.orders FOR
SELECT USING (auth.uid() = user_id);
-- 3. FIX ENROLLMENTS VISIBILITY (Double Check)
-- Ensure Admin can see all enrollments too.
DROP POLICY IF EXISTS "Admin Read Enrollments" ON public.enrollments;
CREATE POLICY "Admin Read Enrollments" ON public.enrollments FOR ALL USING (
    auth.jwt()->>'email' = 'vishal.pandey1912@gmail.com'
);